# YAML file parsers treats scientific notaiton as strings
#Configuration for training baseline ResNet-56 on CIFAR 10
#See Section 4.2 of Deep Residual Learning for Image Classification for settings

# Iterations, etc
numEpochToTrain: 4
batchSizePerWorker: 32
numThreadsPerWorker: 28
numPhaseToTrain: 3
# Learning rates

#From the Accurate, Large minibatch SGD
#'We start from a learning rate of eta, and increment it by a constant amount at each iteration
#such that it reaches eta_hat = k * eta after 5 epochs' (2.2, Gradual warmup)
#'eta = 0.1 * k * n / 256', where n is 32, and n is 8 (5.1)
#

lrInitialBase: 0.0001
lrPeakBase: 0.0001
lrWarmupEpochs: 1
lrStepSize: 2
lrReductionFactor: 0.1
lrMomentum: 0.9
lrMPAdjustmentWarmUpEpochs: 1

# Loss contribution
enableLossActivation: False
enableLossWeightL1: False
enableLossWeightL2: True
lossActivationLambda: 0.00002
lossWeightL1Lambda: 0.00002
lossWeightL2Lambda: 0.0001

# Pruning and quantization parameters
prune: True
pruneCluster: 2
pruneRangeInCluster: 4
sparsityIncrement: 0.25
pruneThreshold: 0.005
quantize: False
numUpdateBNStatsEpochs: 100
numUpdateQatObserverEpochs: 100

# See
seed: 47

# Dataset location
dataTrainDir: '/homes/jmusel/jmuse/imagenet/train'
dataValDir: '/homes/jmusel/jmuse/imagenet/val'

# Checkpoints
checkpointSaveDir: 'experiment_logs/imagenet_resnet50_pretrained_iter_BPc2r4_log'
checkpointSaveFileNameFormat: 'ckpt_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/imagenet_resnet50_pretrained_iter_BPc2r4_log'