channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=20.0
  - cudatoolkit=10.1
  - python=3.6.10
  - pytorch=1.5.0
  - setuptools=46.4.0=py36_0
  - torchvision=0.6.0
  - pip:
    - -r file:requirements.txt

