# YAML file parsers treats scientific notaiton as strings

# Iterations, etc
numEpochToTrain: 100
batchSizePerWorker: 64
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.001
lrPeakBase: 0.01
lrWarmupEpochs: 5
lrStepSize: 10
lrReductionFactor: 0.9
lrMomentum: 0.5
lrMPAdjustmentWarmUpEpochs: 0

# Loss contribution
enableLossActivation: False
enableLossWeightL1: False
enableLossWeightL2: False
lossActivationLambda: 0.00002
lossWeightL1Lambda: 0.00002
lossWeightL2Lambda: 0.00002

# Pruning and quantization parameters
prune: False
pruneCluster: 1
pruneThreshold: 0.005
quantize: False
numUpdateBNStatsEpochs: 100
numUpdateQatObserverEpochs: 100

# See
seed: 47

# Dataset location
dataTrainDir: 'datasets'
dataValDir: 'datasets'

# Checkpoints
checkpointSaveDir: 'experiment_logs/LeNet5_baseline_ckpt'
checkpointSaveFileNameFormat: 'ckpt_LeNet5_baseline_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/LeNet5_baseline_log'