# YAML file parsers treats scientific notaiton as strings

# Iterations, etc
numEpochToTrain: 10
batchSizePerWorker: 64
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.01
lrPeakBase: 0.01
lrWarmupEpochs: 1
lrStepSize: 10
lrReductionFactor: 0.7
lrMomentum: 0.5
lrMPAdjustmentWarmUpEpochs: 5

# Loss contribution
enableLossActivation: True
enableLossWeightL1: True
enableLossWeightL2: True
lossActivationLambda: 0.00002
lossWeightL1Lambda: 0.00002
lossWeightL2Lambda: 0.00002

# Pruning and quantization parameters
prune: False
pruneCluster: 1
pruneThreshold: 0.005
quantize: False
numUpdateBNStatsEpochs: 100
numUpdateQatObserverEpochs: 100

# See
seed: 47

# Dataset location
dataTrainDir: 'datasets'
dataValDir: 'datasets'

# Checkpoints
checkpointSaveDir: 'experiment_logs'
checkpointSaveFileNameFormat: 'ckpt_LeNet_test_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/lenet_test'