# YAML file parsers treats scientific notaiton as strings

# Iterations, etc
numEpochToTrain: 10
batchSizePerWorker: 64
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.01
lrPeakBase: 0.01
lrWarmupEpochs: 1
lrStepSize: 10
lrReductionFactor: 0.7
lrMomentum: 0.5
lrMPAdjustmentWarmUpEpochs: 5

# Loss contribution
enableLossActivation: False
enableLossWeightL1: False
enableLossWeightL2: False
lossActivationLambda: 0.002
lossWeightL1Lambda: 0.002
lossWeightL2Lambda: 0.002

# Pruning paramters
prune: False
pruneCluster: 1
pruneThreshold: 0.005
quantize: False

# See
seed: 47

# Dataset location
dataTrainDir: 'datasets'
dataValDir: 'datasets'

# Checkpoints
checkpointSaveDir: 'experiment_logs'
checkpointSaveFileNameFormat: 'ckpt_LeNet_test_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/lenet_test'