# YAML file parsers treats scientific notaiton as strings
#Configuration for training baseline ResNet-56 on CIFAR 10
#See Section 4.2 of Deep Residual Learning for Image Classification for settings

# Iterations, etc
numEpochToTrain: 160
batchSizePerWorker: 128
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.1
lrPeakBase: 0.1
lrWarmupEpochs: 40
lrStepSize: 40
lrReductionFactor: 0.1
lrMomentum: 0.9
lrMPAdjustmentWarmUpEpochs: 5

# Loss contribution
enableLossActivation: False
enableLossWeightL1: False
enableLossWeightL2: True
lossActivationLambda: 0.00002
lossWeightL1Lambda: 0.00002
lossWeightL2Lambda: 0.0001

# Pruning and quantization parameters
prune: False
pruneCluster: 4
pruneThreshold: 0.005
quantize: False
numUpdateBNStatsEpochs: 100
numUpdateQatObserverEpochs: 100

# See
seed: 47

# Dataset location
dataTrainDir: '/homes/jmusel/jmuse/datasets'
dataValDir: '/homes/jmusel/jmuse/datasets'

# Checkpoints
checkpointSaveDir: 'experiment_logs/cifar10_resnet56_baseline_log'
checkpointSaveFileNameFormat: 'ckpt_cifar10_resnet56_baseline_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/cifar10_resnet56_baseline_log'