# YAML file parsers treats scientific notaiton as strings

# Iterations, etc
numEpochToTrain: 40
batchSizePerWorker: 64
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.005
lrPeakBase: 0.005
lrWarmupEpochs: 1
lrStepSize: 10
lrReductionFactor: 1.0
lrMomentum: 0.5
lrMPAdjustmentWarmUpEpochs: 0

# Loss contribution
enableLossActivation: True
enableLossWeightL1: True
enableLossWeightL2: True
lossActivationLambda: 0.00004
lossWeightL1Lambda: 0.0002
lossWeightL2Lambda: 0.0002

# Pruning and quantization parameters
prune: False
pruneCluster: 4
pruneThreshold: 0.005
quantize: False
numUpdateBNStatsEpochs: 100
numUpdateQatObserverEpochs: 100

# See
seed: 47

# Dataset location
dataTrainDir: '/homes/jmusel/jmuse/datasets'
dataValDir: '/homes/jmusel/jmuse/datasets'

# Checkpoints
checkpointSaveDir: 'experiment_ckpt/LeNet5_sparsify_cluster4_ckpt'
checkpointSaveFileNameFormat: 'ckpt_LeNet5_sparsify_cluster4_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/LeNet5_sparsify_cluster4_log'