# YAML file parsers treats scientific notaiton as strings
#Configuration for training baseline ResNet-56 on CIFAR 10
#See Section 4.2 of Deep Residual Learning for Image Classification for settings

# Iterations, etc
numEpochToTrain: 30
batchSizePerWorker: 128
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.001
lrPeakBase: 0.001
lrWarmupEpochs: 0
lrStepSize: 20
lrReductionFactor: 0.2
lrMomentum: 0.9
lrMPAdjustmentWarmUpEpochs: 0

# Loss contribution
enableLossActivation: True
enableLossWeightL1: True
enableLossWeightL2: True
lossActivationLambda: 0.000003
lossWeightL1Lambda: 0.00008
lossWeightL2Lambda: 0.0001

# Pruning and quantization parameters
prune: True
pruneCluster: 4
pruneThreshold: 0.005
quantize: True
numUpdateBNStatsEpochs: 10
numUpdateQatObserverEpochs: 15

# See
seed: 47

# Dataset location
dataTrainDir: '/homes/jmusel/jmuse/datasets'
dataValDir: '/homes/jmusel/jmuse/datasets'

# Checkpoints
checkpointSaveDir: 'experiment_logs/cifar10_resnet56_quantize_prune_2_log'
checkpointSaveFileNameFormat: 'ckpt_cifar10_resnet56_quantize_prune_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/cifar10_resnet56_quantize_prune_2_log'