# YAML file parsers treats scientific notaiton as strings

# Iterations, etc
numEpochToTrain: 4
batchSizePerWorker: 64
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.01
lrPeakBase: 0.01
lrWarmupEpochs: 1
lrStepSize: 10
lrReductionFactor: 1.0
lrMomentum: 0.5
lrMPAdjustmentWarmUpEpochs: 0

# Loss contribution
enableLossActivation: True
enableLossWeightL1: False
enableLossWeightL2: True
lossActivationLambda: 0.0002
lossWeightL1Lambda: 0.002
lossWeightL2Lambda: 0.002

# Pruning and quantization parameters
prune: True
pruneCluster: 4
pruneThreshold: 0.005
quantize: False
numUpdateBNStatsEpochs: 100
numUpdateQatObserverEpochs: 100

# See
seed: 47

# Dataset location
dataTrainDir: '/homes/jmusel/jmuse/datasets'
dataValDir: '/homes/jmusel/jmuse/datasets'

# Checkpoints
checkpointSaveDir: 'experiment_logs/LeNet5_prune_cluster4_log'
checkpointSaveFileNameFormat: 'ckpt_LeNet5_prune_cluster4_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/LeNet5_prune_cluster4_log'