# YAML file parsers treats scientific notaiton as strings

# Iterations, etc
numEpochToTrain: 10
numPhaseToTrain: 1
batchSizePerWorker: 64
numThreadsPerWorker: 28

# Learning rates
lrInitialBase: 0.01
lrPeakBase: 0.04
lrWarmupEpochs: 1
lrStepSize: 1
lrReductionFactor: 1.0
lrMomentum: 0.5
lrMPAdjustmentWarmUpEpochs: 1

# Loss contribution
enableLossActivation: False
enableLossWeightL1: False
enableLossWeightL2: True
lossActivationLambda: 0.00002
lossWeightL1Lambda: 0.00002
lossWeightL2Lambda: 0.00002

# Pruning and quantization parameters
prune: False
pruneCluster: 2
pruneRangeInCluster: 8
sparsityIncrement: 0.125
pruneThreshold: 0.005
quantize: True
numUpdateBNStatsEpochs: 5
numUpdateQatObserverEpochs: 6

# See
seed: 47

# Dataset location
dataTrainDir: '/homes/jmusel/jmuse/datasets'
dataValDir: '/homes/jmusel/jmuse/datasets'

# Checkpoints
checkpointSaveDir: 'experiment_logs/lenet_test_quantize_log'
checkpointSaveFileNameFormat: 'ckpt_LeNet_test_quantize_epoch{}.pth.tar'

# Log Dir
logDir: 'experiment_logs/lenet_test_quantize_log'