# YAML file parsers treats scientific notaiton as strings
#Configuration for pruning ResNet-50 on ImageNet
#See Section 4.2 of Deep Residual Learning for Image Classification for settings

# Iterations, etc
numEpochToTrain: 6
batchSizePerWorker: 32
numThreadsPerWorker: 8
numPhaseToTrain: 1
# Learning rates1

lrInitialBase: 0.0001
lrPeakBase: 0.0001
lrWarmupEpochs: 1
lrStepSize: 4
lrReductionFactor: 0.1
lrMomentum: 0.9
lrMPAdjustmentWarmUpEpochs: 1

# Loss contribution
enableLossActivation: False
enableLossWeightL1: False
enableLossWeightL2: True
lossActivationLambda: 0.00002
lossWeightL1Lambda: 0.00002
lossWeightL2Lambda: 0.0001

# Pruning and quantization parameters
prune: False
pruneCluster: 2
pruneRangeInCluster: 4
sparsityIncrement: 0.25
pruneThreshold: 0.005
quantize: True
numUpdateBNStatsEpochs: 1
numUpdateQatObserverEpochs: 2

# See
seed: 47

# Dataset location
dataTrainDir: '/homes/jmusel/jmuse/imagenet/train'
dataValDir: '/homes/jmusel/jmuse/imagenet/val'

# Checkpoints
checkpointSaveDir: '/homes/jmusel/jmuse/vgg16_logs/imagenet_vgg16_pretrained_iter_BPc2r4_p50_quantize'
checkpointSaveFileNameFormat: 'ckpt_epoch{}.pth.tar'

# Log Dir
logDir: '/homes/jmusel/jmuse/vgg16_logs/imagenet_vgg16_pretrained_iter_BPc2r4_p50_quantize'